"""Local model backend — Protocol and fake implementation.

Design reference: §5.9, ADR-002

The LocalModelBackend Protocol defines the interface for local model calls.
FakeLocalModelBackend provides a configurable test double for all automated
tests — no GPU or llama.cpp required.
"""

from __future__ import annotations

import json
from typing import Any, Protocol, runtime_checkable

from .errors import LOCAL_MODEL_ERROR, PublicError

# ── Backend Protocol ────────────────────────────────────────────────────────


@runtime_checkable
class LocalModelBackend(Protocol):
    """Protocol for local model backends.

    Implementations call a local LLM (llama.cpp, Ollama, etc.) and return
    a JSON string representing an operation batch.
    """

    async def generate_operation_batch(
        self,
        system_prompt: str,
        user_prompt: str,
        schema: dict[str, Any],
    ) -> str:
        """Generate a structured JSON operation batch.

        Args:
            system_prompt: System-level instructions for the model.
            user_prompt: The user prompt (slice + context).
            schema: JSON Schema constraint for the response format.

        Returns:
            A JSON string conforming to the schema.

        Raises:
            PublicError (LOCAL_MODEL_ERROR): On network or model failure.
        """
        ...


# ── Default canned response ─────────────────────────────────────────────────

_DEFAULT_CANNED_RESPONSE: str = json.dumps(
    {
        "schema_id": "forgerwrite.operation_batch.v1",
        "batch_id": "fake-batch-001",
        "slice_id": "fake-slice",
        "operations": [
            {
                "op": "create_file",
                "path": "src/generated.rs",
                "content": "// generated by FakeLocalModelBackend\n",
            }
        ],
    }
)

_INVALID_JSON_SIMULATION: str = "NOT VALID JSON {{{"

# ── Failure simulation identifiers ──────────────────────────────────────────

_FAILURE_INVALID_JSON: str = "invalid_json"
_FAILURE_NETWORK_ERROR: str = "network_error"


class FakeLocalModelBackend:
    """Configurable test double implementing LocalModelBackend.

    Supports:
    - Canned JSON responses
    - Simulated failures (invalid JSON, network errors) in FIFO order
    - Attempt logging for test inspection

    All automated tests use this — no GPU needed.
    """

    def __init__(
        self,
        canned_response: str | None = None,
        failure_simulations: list[str] | None = None,
    ) -> None:
        self._canned: str = canned_response or _DEFAULT_CANNED_RESPONSE
        self._failures: list[str] = list(failure_simulations or [])
        self.attempt_log: list[dict[str, Any]] = []

    async def generate_operation_batch(
        self,
        system_prompt: str,
        user_prompt: str,
        schema: dict[str, Any],
    ) -> str:
        """Return canned response or simulate a failure.

        Failures are consumed FIFO from the failure_simulations queue.
        Once the queue is empty, returns the canned response.
        """
        attempt: dict[str, Any] = {
            "system_prompt": system_prompt,
            "user_prompt": user_prompt,
            "schema": schema,
        }

        if self._failures:
            failure = self._failures.pop(0)
            if failure == _FAILURE_INVALID_JSON:
                attempt["status"] = "failure"
                attempt["response"] = _INVALID_JSON_SIMULATION
                self.attempt_log.append(attempt)
                return _INVALID_JSON_SIMULATION
            if failure == _FAILURE_NETWORK_ERROR:
                attempt["status"] = "failure"
                attempt["error"] = "Simulated network error"
                self.attempt_log.append(attempt)
                raise PublicError(
                    code=LOCAL_MODEL_ERROR,
                    message="Simulated network error",
                    hint="Fake backend network failure simulation.",
                )

        attempt["status"] = "success"
        attempt["response"] = self._canned
        self.attempt_log.append(attempt)
        return self._canned
